create table if not exists public.cms_packages (
  id bigint generated by default as identity primary key,
  name text not null,
  price text not null,
  original_price text,
  is_promotion boolean not null default false,
  popular boolean not null default false,
  schedules jsonb not null default '[]'::jsonb,
  includes jsonb not null default '[]'::jsonb,
  extras jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_gallery_images (
  id bigint generated by default as identity primary key,
  src text not null,
  alt text not null,
  category text not null,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  image text not null,
  image_alt text not null default '',
  date date not null default current_date,
  read_time text not null default '5 min',
  category text not null default 'Dicas',
  tags jsonb not null default '[]'::jsonb,
  content text not null default '',
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_testimonials (
  id bigint generated by default as identity primary key,
  text text not null,
  author text not null,
  location text,
  rating integer not null default 5 check (rating between 1 and 5),
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.cms_packages enable row level security;
alter table public.cms_gallery_images enable row level security;
alter table public.cms_blog_posts enable row level security;
alter table public.cms_faqs enable row level security;
alter table public.cms_testimonials enable row level security;

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users for select
to authenticated
using (app_private.is_admin());

drop policy if exists "Public can read published packages" on public.cms_packages;
create policy "Public can read published packages"
on public.cms_packages for select
to anon, authenticated
using (is_published = true or app_private.is_admin());

drop policy if exists "Admins can manage packages" on public.cms_packages;
create policy "Admins can manage packages"
on public.cms_packages for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

drop policy if exists "Public can read published gallery images" on public.cms_gallery_images;
create policy "Public can read published gallery images"
on public.cms_gallery_images for select
to anon, authenticated
using (is_published = true or app_private.is_admin());

drop policy if exists "Admins can manage gallery images" on public.cms_gallery_images;
create policy "Admins can manage gallery images"
on public.cms_gallery_images for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

drop policy if exists "Public can read published blog posts" on public.cms_blog_posts;
create policy "Public can read published blog posts"
on public.cms_blog_posts for select
to anon, authenticated
using (is_published = true or app_private.is_admin());

drop policy if exists "Admins can manage blog posts" on public.cms_blog_posts;
create policy "Admins can manage blog posts"
on public.cms_blog_posts for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

drop policy if exists "Public can read published FAQs" on public.cms_faqs;
create policy "Public can read published FAQs"
on public.cms_faqs for select
to anon, authenticated
using (is_published = true or app_private.is_admin());

drop policy if exists "Admins can manage FAQs" on public.cms_faqs;
create policy "Admins can manage FAQs"
on public.cms_faqs for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

drop policy if exists "Public can read published testimonials" on public.cms_testimonials;
create policy "Public can read published testimonials"
on public.cms_testimonials for select
to anon, authenticated
using (is_published = true or app_private.is_admin());

drop policy if exists "Admins can manage testimonials" on public.cms_testimonials;
create policy "Admins can manage testimonials"
on public.cms_testimonials for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

insert into storage.buckets (id, name, public)
values ('cms-media', 'cms-media', true)
on conflict (id) do nothing;

drop policy if exists "Public can read CMS media" on storage.objects;
create policy "Public can read CMS media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'cms-media');

drop policy if exists "Admins can upload CMS media" on storage.objects;
create policy "Admins can upload CMS media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'cms-media' and app_private.is_admin());

drop policy if exists "Admins can update CMS media" on storage.objects;
create policy "Admins can update CMS media"
on storage.objects for update
to authenticated
using (bucket_id = 'cms-media' and app_private.is_admin())
with check (bucket_id = 'cms-media' and app_private.is_admin());

drop policy if exists "Admins can delete CMS media" on storage.objects;
create policy "Admins can delete CMS media"
on storage.objects for delete
to authenticated
using (bucket_id = 'cms-media' and app_private.is_admin());

insert into public.admin_users (email)
values ('espacogirafinha@gmail.com')
on conflict (email) do nothing;
