create table if not exists public.reservation_leads (
  id bigint generated by default as identity primary key,
  child_name text,
  parent_name text not null,
  phone text not null,
  email text,
  event_date date,
  event_time text,
  package_name text,
  guests_count integer,
  message text,
  status text not null default 'novo' check (status in ('novo', 'contactado', 'reservado', 'pago', 'concluido')),
  source text not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reservation_leads enable row level security;

drop policy if exists "Public can create reservation leads" on public.reservation_leads;
create policy "Public can create reservation leads"
on public.reservation_leads for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read reservation leads" on public.reservation_leads;
create policy "Admins can read reservation leads"
on public.reservation_leads for select
to authenticated
using (app_private.is_admin());

drop policy if exists "Admins can update reservation leads" on public.reservation_leads;
create policy "Admins can update reservation leads"
on public.reservation_leads for update
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

drop policy if exists "Admins can delete reservation leads" on public.reservation_leads;
create policy "Admins can delete reservation leads"
on public.reservation_leads for delete
to authenticated
using (app_private.is_admin());
